name: test-nesta

services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'test-nesta'
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - database-pg:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  database-pg: